package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.MSBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.msBuild
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.nuGetInstaller
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'XamarinFormsStocksApp'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("XamarinFormsStocksApp")) {
    expectSteps {
        nuGetInstaller {
            toolPath = "%teamcity.tool.NuGet.CommandLine.5.5.0%"
            projects = "CS/Stocks.sln"
            noCache = true
            sources = "../../packages"
        }
        msBuild {
            path = "CS/Stocks.sln"
            targets = "clean,build"
        }
    }
    steps {
        update<MSBuildStep>(1) {
            version = MSBuildStep.MSBuildVersion.MONO_v4_5
            toolsVersion = MSBuildStep.MSBuildToolsVersion.V4_0
        }
    }
}
