package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'XamarinDataForm201'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("XamarinDataForm201")) {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
